"""Add token counting fields

Revision ID: 910c8a7b34fa
Revises: 002
Create Date: 2025-07-24 14:11:50.926682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910c8a7b34fa'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'total_tokens')
    op.drop_column('stories', 'output_tokens')
    op.drop_column('stories', 'input_tokens')
    op.drop_column('chat_messages', 'total_tokens')
    op.drop_column('chat_messages', 'output_tokens')
    op.drop_column('chat_messages', 'input_tokens')
    # ### end Alembic commands ###